fix: rename files asynchronously
AndroidIDEOfficial/AndroidIDE pull request #1439
Opened 2023-11-09 15:25 UTC by raredeveloper

2023-11-09 15:29 UTC, MrIkso commented on app/src/main/java/com/itsaky/androidide/actions/filetree/RenameAction.kt
> +          ProgressDialog.show(context, null, context.getString(com.itsaky.androidide.resources.R.string.please_wait), true, false)
ProgressDialog is deprecated

2023-11-09 16:00 UTC, raredeveloper commented on app/src/main/java/com/itsaky/androidide/actions/filetree/RenameAction.kt
> +          ProgressDialog.show(context, null, context.getString(com.itsaky.androidide.resources.R.string.please_wait), true, false)
The same is used in "DeleteAction".

2023-11-10 16:12 UTC, raredeveloper commented on app/src/main/java/com/itsaky/androidide/actions/filetree/RenameAction.kt
> +      executeAsync({ name.length in 1..40 && FileUtils.rename(file, name) }) {
Okay

2023-11-10 18:14 UTC, raredeveloper commented on app/src/main/java/com/itsaky/androidide/actions/filetree/RenameAction.kt
> +      executeAsync({ name.length in 1..40 && FileUtils.rename(file, name) }) {
There is a problem: if the user collapses the parent node and expands it again while renaming the renamed file node will not be updated

2023-11-10 18:29 UTC, itsaky requested changes

2023-11-10 18:29 UTC, itsaky commented on app/src/main/java/com/itsaky/androidide/actions/filetree/RenameAction.kt
> +              notifyFileRenamed(file, name, context)
You can safely move `notifyFileRenamed` outside of the `Main` context. For `notifyFileRenamed`, EventBus will dispatch the event on the event receiver's preferred thread.

2023-11-10 19:02 UTC, itsaky approved these changes

2023-11-11 14:33 UTC, merged

2023-11-11 14:33 UTC, itsaky commented
Thank you for your contributions.