Update Portuguese strings
AndroidIDEOfficial/AndroidIDE pull request #456
Opened 2022-09-21 21:23 UTC by FrioGitHub

2022-09-24 05:19 UTC, deepkrg17 commented on app/src/main/res/values-pt-rBR/strings.xml
> -  <string name="idepref_editor_useSoftTabs_summary">Escolha se deseja usar espaços em vez de caracteres de tabulação (\\t).</string>
Don't change, '\\' is the escape character for '\' .

2022-09-24 05:30 UTC, deepkrg17 requested changes
Don't change. It's an escape character. '\\\\' -> '\\'

2022-09-24 14:00 UTC, FrioGitHub commented
> Don't change. It's an escape character. '\\' -> '\'

ok

2022-09-24 20:29 UTC, olhotorto commented
Tem telegram? @FrioGitHub

2022-09-24 20:39 UTC, FrioGitHub commented
> Tem telegram? @FrioGitHub

tenho, estou no servidor do AndroidIDE, meu user é Frio

2022-10-24 07:24 UTC, itsaky approved these changes

2022-10-24 07:25 UTC, merged

2022-10-24 07:25 UTC, itsaky commented
Thanks for your contribution. Sorry for the delay.